# Default values for watchapi
replicaCount: 1

image:
  repository: ghcr.io/username/api-monitoring
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: watchapi.dev
      paths:
        - path: /
          pathType: Prefix
    - host: www.watchapi.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: watchapi-tls
      hosts:
        - watchapi.dev
        - www.watchapi.dev

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Application specific configuration
app:
  nodeEnv: production
  port: 3000
  hostname: "0.0.0.0"
  nextTelemetryDisabled: 1

# Database configuration
database:
  url: ""

# JWT configuration
jwtSecret: ""

# Next.js public configuration
nextPublicDomain: "https://watchapi.dev"

# Monitoring configuration
enableCron: "true"
defaultCheckInterval: "300000"  # 5 minutes
maxTimeout: "30000"  # 30 seconds

# OAuth configuration (optional)
oauth:
  google:
    clientId: ""
    clientSecret: ""
  github:
    clientId: ""
    clientSecret: ""
