apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "watchapi.fullname" . }}
  labels:
    {{- include "watchapi.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "watchapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "watchapi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "watchapi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            - name: ENABLE_CRON
              value: {{ .Values.enableCron | quote }}
            - name: DEFAULT_CHECK_INTERVAL
              value: {{ .Values.defaultCheckInterval | quote }}
            - name: MAX_TIMEOUT
              value: {{ .Values.maxTimeout | quote }}
            - name: NODE_ENV
              value: {{ .Values.app.nodeEnv | quote }}
            - name: PORT
              value: {{ .Values.app.port | quote }}
            - name: HOSTNAME
              value: {{ .Values.app.hostname | quote }}
            - name: NEXT_TELEMETRY_DISABLED
              value: {{ .Values.app.nextTelemetryDisabled | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "watchapi.fullname" . }}-secret
                  key: database-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "watchapi.fullname" . }}-secret
                  key: jwt-secret
            - name: NEXT_PUBLIC_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "watchapi.fullname" . }}-config
                  key: next-public-domain
            {{- if .Values.oauth.google.clientId }}
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "watchapi.fullname" . }}-secret
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "watchapi.fullname" . }}-secret
                  key: google-client-secret
            {{- end }}
            {{- if .Values.oauth.github.clientId }}
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "watchapi.fullname" . }}-secret
                  key: github-client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "watchapi.fullname" . }}-secret
                  key: github-client-secret
            {{- end }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: ghcr-secret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}